service: genyo
app: genio
org: leonardofalco
frameworkVersion: '2'

package:
  excludeDevDependencies: true


plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  lambdaHashingVersion: 20201221
  memorySize: 1024
  timeout: 120
  logRetentionInDays: 14
  versionFunctions: false
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  environment:
    TZ: America/Sao_Paulo

functions:
  hit-point:
    handler: src/handlers/hit-point/handler.handler
    timeout: 120

