service: genyo
app: genio
org: leonardofalco
frameworkVersion: '2'

package:
  excludeDevDependencies: false


plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  lambdaHashingVersion: 20201221
  memorySize: 128
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1

functions:
  hit-point-start-morning:
    handler: src/handlers/hit-point/handler.handler
    timeout: 120
    events:
      - schedule: cron(0 8 ? * MON-FRI *)
    environment:
      POINT_TYPE: start

  hit-point-stop-morning:
    handler: src/handlers/hit-point/handler.handler
    events:
      - schedule: cron(0 12 ? * MON-FRI *)
    environment:
      POINT_TYPE: stop

  hit-point-start-afternoon:
    handler: src/handlers/hit-point/handler.handler
    events:
      - schedule: cron(30 13 ? * MON-FRI *)
    environment:
      POINT_TYPE: start

  hit-point-stop-afternoon:
    handler: src/handlers/hit-point/handler.handler
    events:
      - schedule: cron(30 17 ? * MON-FRI *)
    environment:
      POINT_TYPE: stop