name: Continuous deployment

on:
  push:
    branches:
      - master
      - preview
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install

      - name: deploy
        if: github.ref == 'refs/heads/master'
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npx serverless deploy --stage prod
